# navigation Links
main:
  - name: Home
    url: "#about"
    weight: 10
  - name: Google Scholar
    url: "https://scholar.google.com/citations?hl=en&user=wRydfNQAAAAJ"
    weight: 20
  - name: Publications
    url: "#publications"
    weight: 30
  - name: Awards
    url: "#awards"
    weight: 40
  - name: Contact
    url: "#contact"
    weight: 50

  - name: Curriculum Vitae
    url: uploads/cv.pdf
    weight: 45
